name: build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps: 
      - name: Set up Docker Buildx 
        uses: docker/setup-buildx-action@v1

      -
        name: Login to ghcr.io
        uses: docker/login-action@v1
        with: 
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build container and push to ghcr.io
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ghcr.io/iofq/nvim:latest
      -
        name: Extract .tar.gz from container
        uses: shrink/actions-docker-extract@v1
        id: extract
        with:
          image: ghcr.io/iofq/nvim:latest
          path: /app/neovim-x86_64-linux.AppImage
      -
        name: Upload archive to release
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ${{ steps.extract.outputs.destination }}
          update_latest_release: true
          overwrite: true
