name: build

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Run `nix bundle`
        id: build
        run: |
          nix bundle \
              -o nvim.AppImage \
              --bundler github:ralismark/nix-appimage \
              --extra-experimental-features nix-command \
              --extra-experimental-features flakes .#full
          nix bundle \
              -o nvim-minimal.AppImage \
              --bundler github:ralismark/nix-appimage \
              --extra-experimental-features nix-command \
              --extra-experimental-features flakes .#minimal

      - name: Upload bundle to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: /*.AppImage
          overwrite: true
